import { FC, memo } from 'react';
import Container from '@material-ui/core/Container';
import Head from 'next/head';
//
import Header from '../../components/Header';
import Footer from '../Footer';
//
import styles from './style.module.scss';

type Props = {
	children: any;
	container?: boolean;
};

const Layout: FC<Props> = ({ container = true, children }) => {
	return (
		<>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />

				<title>Homepage</title>
			</Head>

			<Header />

			{container ? (
				<Container className={styles.Layout} maxWidth="lg" disableGutters>
					{children}
				</Container>
			) : (
				<>{children}</>
			)}

			<Footer />
		</>
	);
};

export default memo(Layout);
